//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webcuoiky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cattable
    {
        public int catid { get; set; }
        public string catname { get; set; }
        public string catdesc { get; set; }
    }
}
