//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webcuoiky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerTbl
    {
        public int SellerId { get; set; }
        public string SellerName { get; set; }
        public int SellerAge { get; set; }
        public string SellerPhone { get; set; }
    }
}
